"""Send the daily summary email via SendGrid."""

import os
from datetime import datetime

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Content

RECIPIENT = "connor.smith@atlan.com"


def send_summary_email(summary_text: str, date: datetime) -> None:
    """Send the daily summary as an HTML email."""
    api_key = os.environ.get("SENDGRID_API_KEY")
    if not api_key:
        raise EnvironmentError("SENDGRID_API_KEY is not set.")

    sender = os.environ.get("SENDGRID_SENDER_EMAIL", "daily-summary@connor5101520.github.io")
    date_str = date.strftime("%A, %B %d")

    html_body = _build_html(summary_text, date_str)

    message = Mail(
        from_email=sender,
        to_emails=RECIPIENT,
        subject=f"Your Daily Summary — {date_str}",
        html_content=Content("text/html", html_body),
    )

    sg = SendGridAPIClient(api_key)
    response = sg.send(message)
    print(f"Email sent: status {response.status_code}")


def _build_html(summary: str, date_str: str) -> str:
    """Convert the markdown-ish summary into a clean HTML email."""
    import re

    # Convert markdown-style formatting to HTML
    html = summary
    html = re.sub(r"^### (.+)$", r"<h3 style='color:#2d3748;margin-top:16px'>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2 style='color:#1a202c;margin-top:20px'>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"^- (.+)$", r"<li style='margin-bottom:4px'>\1</li>", html, flags=re.MULTILINE)
    html = html.replace("\n\n", "</p><p style='margin:8px 0'>")
    html = html.replace("\n", "<br>")

    return f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
                max-width:600px;margin:0 auto;padding:24px;color:#2d3748">
        <div style="border-bottom:2px solid #4a5568;padding-bottom:12px;margin-bottom:20px">
            <h1 style="margin:0;font-size:22px;color:#1a202c">Daily Summary</h1>
            <p style="margin:4px 0 0;color:#718096;font-size:14px">{date_str}</p>
        </div>
        <div style="font-size:15px;line-height:1.6">
            <p style="margin:8px 0">{html}</p>
        </div>
        <div style="border-top:1px solid #e2e8f0;margin-top:24px;padding-top:12px;
                    font-size:12px;color:#a0aec0">
            Generated by your Daily Summary Bot
        </div>
    </div>
    """
